# Generated by Django 4.1.1 on 2023-06-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('img_url', models.URLField(null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('preferred_transportation', models.CharField(choices=[('BUS', 'Bus'), ('JEEP', 'Jeep'), ('OTHER', 'Other')], max_length=100)),
                ('interested_in', models.CharField(choices=[('NAT', 'Nature'), ('CUL', 'Culture'), ('TRA', 'Tradition'), ('REL', 'Religion'), ('WAT', 'Waterfalls')], max_length=100)),
                ('religion', models.CharField(choices=[('CHR', 'Christianity'), ('ISL', 'Islam'), ('HIN', 'Hinduism'), ('BUD', 'Buddhism'), ('JEW', 'Judaism'), ('OTH', 'Other')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('img_url', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('Religious', 'Religious'), ('Cultural', 'Cultural'), ('Dating', 'Dating')], max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.location')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('img_url', models.URLField(null=True)),
                ('start_location', models.CharField(max_length=100, null=True)),
                ('end_location', models.CharField(max_length=100, null=True)),
                ('mode_of_transportation', models.CharField(max_length=100, null=True)),
                ('accomodation', models.CharField(max_length=100, null=True)),
                ('ageRange', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('Religious', 'Religious'), ('Cultural', 'Cultural'), ('Dating', 'Dating')], max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.location')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.site')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('available_seats', models.PositiveIntegerField()),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.plan')),
            ],
        ),
    ]
