# Generated by Django 4.1.1 on 2023-06-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHub', '0002_availability_title_plan_title_alter_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='guide_type',
            field=models.CharField(choices=[('Full Guided', 'Full Guided'), ('Partial Guided', 'Partial Guided'), ('None', 'None')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
