# Generated by Django 4.1.1 on 2023-06-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EHub', '0003_plan_duration_plan_guide_type_alter_plan_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EHub.location'),
        ),
    ]
