# Generated by Django 4.1.1 on 2023-06-30 14:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EHub', '0005_sitecategory_alter_plan_type_remove_site_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Describe something.Dont repeat yourself.', null=True),
        ),
    ]
