# Generated by Django 4.1.1 on 2023-06-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHub', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='location',
        ),
        migrations.AlterField(
            model_name='plan',
            name='accomodation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='mode_of_transportation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
