# Generated by Django 4.1.1 on 2023-06-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EHub', '0008_remove_plan_location_alter_plan_accomodation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='type',
            new_name='site_type',
        ),
    ]
