# Generated by Django 4.1.1 on 2023-06-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHub', '0009_rename_type_site_site_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
