# Generated by Django 4.1.1 on 2023-06-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHub', '0010_plan_city_plan_district_plan_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('img_url', models.URLField(null=True)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100, null=True)),
                ('venue', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('Paragliding', 'Paragliding'), ('Bunjee Jumping', 'Bunjee Jumping'), ('Safari', 'Safari'), ('Boating', 'Boating'), ('Tour', 'Tour')], max_length=300, null=True),
        ),
    ]
