# Generated by Django 4.1.1 on 2023-06-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHub', '0011_event_alter_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
