# Generated by Django 4.1.1 on 2023-06-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EHub', '0012_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Cultural', 'Cultural'), ('Religion', 'Religion'), ('Festival', 'Festival')], max_length=100, null=True),
        ),
    ]
